### ISSUE TITLE
encountered problems when running your model, pls help

### ISSUE THREAD

**Issue by yif-fast** [akshaypai/tfClassifier#15]
Hi There,

I use the following for training, it works well:
`python retrain_new.py --image_dir ./DataSet --output_graph ./output_dir/output_graph.pb --output_labels ./output_dir/output_labels.txt --summaries_dir ./output_dir/retrain_logs --how_many_training_steps 600 --learning_rate 0.01 --testing_percentage 10 --validation_percentage 10 --model_dir ./inception --bottleneck_dir ./output_dir`

When I run the following to do the classfiying test:
`python retrain_model_classifier.py ./test_img/2222.jpg`

It raise the following error:
`Traceback (most recent call last):
  File "retrain_model_classifier.py", line 12, in <module>
    in tf.gfile.GFile("./labels.txt")]
  File "retrain_model_classifier.py", line 11, in <listcomp>
    label_lines = [line.rstrip() for line
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 220, in __next__
    return self.next()
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 214, in next
    retval = self.readline()
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 183, in readline
    self._preread_check()
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: ./labels.txt : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4\udcceļ\udcfe\udca1\udca3
; No such file or directory`

I guess I missed some arguments when running **retrain_model_classifier.py**

Can you pls help on this?

**Comment by sourcedexter** [comment]
Hey, hope the issue is solved. If it is could you please add the solution here?
